name: Deploy to Server

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Project Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload file to server
          uses: wangyucode/sftp-upload-action@v2
          with:
            host: ${{ secrets.SERVER_IP }}
            port: ${{ secrets.SERVER_PORT }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_PASS }}
            localDir: "dist"
            remoteDir: ${{ secrets.SERVER_TARGET_PATH }}
